### ISSUE TITLE
'mathfilters' is not a valid tag library: Template library mathfilters not found, tried 

### ISSUE THREAD

**Issue by suffrage** [dbrgn/django-mathfilters#13]
Install lib, but it is not working

django 1.8.4
osx 10.10.5
python Python 2.7.10 (default, Jul 14 2015, 19:46:27)
![2015-09-21 16 36 17](https://cloud.githubusercontent.com/assets/248433/9993258/82b7ffea-607f-11e5-9513-01cb6e0a1d9a.png)

```python
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
<div class="col-lg-12">
<table class="table table-bordered">
....
{% endblock %}
```

**Comment by dbrgn** [comment]
Did you add 'mathfilters' to `INSTALLED_APPS`?

**Comment by suffrage** [comment]
sorry, no
you can close it
