### ISSUE TITLE
Need update version into pypi

### ISSUE THREAD

**Issue by dicos** [dbrgn/django-mathfilters#14]
Into page https://pypi.python.org/pypi/django-mathfilters last updated 2014-07-22

**Comment by dbrgn** [comment]
Will do!

**Comment by dicos** [comment]
Version is not change and after install from pypi error "Invalid filter: 'addition'" is available

**Comment by dbrgn** [comment]
Yes, because I did not update the version yet.

**Comment by dbrgn** [comment]
Version 0.4.0 is now published, sorry for the delay.

https://pypi.python.org/pypi/django-mathfilters/0.4.0

I switched from distutils to setuptools in the packaging, so if you notice any problems during the installation please let me know.

**Comment by dicos** [comment]
Thank you very much!
