### ISSUE TITLE
Support for Django > 1.8

### ISSUE THREAD

**Issue by torehc** [dbrgn/django-mathfilters#15]
Hi, I think it's a very interesting project to continue with the versions of Django higher than 1.8.

Do you plan to upgrade to the new versions of Django?

Currently it does not work in 1.11. Version 2.0 of Django I have not tried it.

Cheers

**Comment by dbrgn** [comment]
I don't see why it shouldn't work with current Django versions. Pull requests that update the README and package metadata would be welcome :)
