### ISSUE TITLE
Django 2.1.7 No module named 'mathfilters' when adding to INSTALLED_APPS

### ISSUE THREAD

**Issue by tonxxx** [dbrgn/django-mathfilters#18]
I am trying to add 'mathfilters' to my INSTALLED_APPS but getting ModuleNotFoundError: No module named 'mathfilters'

pip list shows that django-mathfilters        0.4.0 is installed

What can be the reason? I am on Windows10 with Python  3.7.2

Thanks!

**Comment by TheNetRunner** [comment]
If you're running a virtual python environment then make sure you're installed to the virtual environment instead of globally.

**Comment by tonxxx** [comment]
Thank! Really, something went wrong with my venv (pip installed packages globally); re-created it and now everything is cool with mathfilters

**Comment by TheNetRunner** [comment]
Happens to the best of us 😊

**Comment by sarathkshatri** [comment]
Hey Guys,

I am also facing the same issue. Please let me know what command do I need to use to fix this issue.

Thanks

**Comment by KeithTt** [comment]
```bash
pip3 install django-mathfilters
```

**Comment by singh932** [comment]
Hi KeithTt,

Thanks for helping me for this issue
