### ISSUE TITLE
How to add total in for loop in template using django-mathfilters?

### ISSUE THREAD

**Issue by raikk** [dbrgn/django-mathfilters#24]
I am trying to perform adding total like this in template

```
total = 0
for stotal in items:
      total = total + stotal.item_price
endfor

print(total)
```

i have tried  and looking for related example but i can't find. 
can i do this in django template using django-mathfilters?

Thank you!

**Comment by dbrgn** [comment]
No, this is out of scope (you'd need to map an itemgetter to the iterable).

It's probably better to precalculate this value in the view and pass it to the template.
