### ISSUE TITLE
How to add two floating values

### ISSUE THREAD

**Issue by nithin69** [dbrgn/django-mathfilters#25]
{{ order.get_total | add:7.99 }}
where order.get_total is 12.99 . I am trying to add 12.99 with 7.99 but while adding getting an output of 19

**Comment by dbrgn** [comment]
What data type is `order.get_total`?

**Comment by dbrgn** [comment]
Oh, by the way, `add` is not even part of `django-mathfilters`, it's a [django built-in](https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#add) and always coerces values to integers. You might want `addition` instead. See the README.
