### ISSUE TITLE
add filters for `min` and `max`

### ISSUE THREAD

**Issue by lsloan** [dbrgn/django-mathfilters#27]
This module has been very helpful to me.

Please consider adding filters for `min` and `max` to return the minimum or maximum of two numbers.  Support for more than two arguments would be appreciated, too.

**Comment by dbrgn** [comment]
Thanks nice words, and for the suggestion!

I don't use this library myself anymore, so I'd like to keep maintenance effort to as little as possible. Therefore I'd rather not add more features.
