### ISSUE TITLE
Division decimal places precision

### ISSUE THREAD

**Issue by Kaszanas** [dbrgn/django-mathfilters#29]
I would like to ask if there is a possibility of controlling how many decimal places there are after a division is performed.

Lets say the following operation would be done:

```
{{ 400|div:100 }}
```

This would result in ```4.0```. How to have more control to render ```4.00``` or ```4```

Any help would be appreciated.

**Comment by dbrgn** [comment]
You could write a custom filter that uses [round](https://docs.python.org/3.8/library/functions.html#round):

    {{ 400|div:100|round:2 }}

**Comment by dbrgn** [comment]
Ah, actually this already exists: https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#floatformat

**Comment by Kaszanas** [comment]
Thank you very much for your assistance! @dbrgn
