### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by eecp** [dbrgn/django-mathfilters#9]
I'm using your filters to pre-compute some number input formfields in my templates. As long as my client browser is set to english the filters work fine, but if it is set to my native language (german) they stop working (empty result). 

Turning of localization ({% localize off %} around the form did solve the problem. So I believe that somewhere in the process the decimal separator becomes incompatible. Any chance to deal with this issue from inside the filter functions?

**Comment by dbrgn** [comment]
Hm, so if I understand it correctly you're passing in localized numbers into the filter?

**Comment by eecp** [comment]
Well if you suggest to just turn off localization i would happily do that, if Django would be able to also turn off the input field localization. Unfortunately this is defined by the client browser. So if i turn off localization (e.g. by settings.py l10n=false) i have "." decimal points in all output fields but still "," decimal point in all input fields. Sure this may be just eye candy, but an annoying one, if you try to get a little professional look to your forms.

**Comment by dbrgn** [comment]
Good point. The filters should primarily be used for presentation purposes. A good use case that comes to my mind is to multiply a value between 0.0-1.0 by 100 to make it a percent-like number.
